// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzqwvuuewqzvtdbtwryh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cXd2dXVld3F6dnRkYnR3cnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODE2OTYsImV4cCI6MjA3MTc1NzY5Nn0.-2FvEunFSdQlpRju4Zuzd0QoGSXy8bU2dhm5MOZT1VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});